// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIE3f9zIxEcYUzSglBbGtxMPh7y_eHt_M',
    appId: '1:976774674289:web:01ffe07ebf93380f3768d0',
    messagingSenderId: '976774674289',
    projectId: 'do-mas-movil-app',
    authDomain: 'do-mas-movil-app.firebaseapp.com',
    databaseURL: 'https://do-mas-movil-app-default-rtdb.firebaseio.com',
    storageBucket: 'do-mas-movil-app.appspot.com',
    measurementId: 'G-LGJ6DRX01E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm0NvpRDnTFW2rH6O2wvVvNmimxiZdLEs',
    appId: '1:976774674289:android:cdad0ed9820785a23768d0',
    messagingSenderId: '976774674289',
    projectId: 'do-mas-movil-app',
    databaseURL: 'https://do-mas-movil-app-default-rtdb.firebaseio.com',
    storageBucket: 'do-mas-movil-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmf2QFY-7D-jeyb0kDE-s_nH2hd4DWvxQ',
    appId: '1:976774674289:ios:e1fcb3d11414182a3768d0',
    messagingSenderId: '976774674289',
    projectId: 'do-mas-movil-app',
    databaseURL: 'https://do-mas-movil-app-default-rtdb.firebaseio.com',
    storageBucket: 'do-mas-movil-app.appspot.com',
    iosClientId: '976774674289-bo45s8oarp7q5859bt9du9b8aeu8fm0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.doMas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmf2QFY-7D-jeyb0kDE-s_nH2hd4DWvxQ',
    appId: '1:976774674289:ios:e1fcb3d11414182a3768d0',
    messagingSenderId: '976774674289',
    projectId: 'do-mas-movil-app',
    databaseURL: 'https://do-mas-movil-app-default-rtdb.firebaseio.com',
    storageBucket: 'do-mas-movil-app.appspot.com',
    iosClientId: '976774674289-bo45s8oarp7q5859bt9du9b8aeu8fm0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.doMas',
  );
}
