// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCT40L6xeX6sfzFW7Ap7HlT2NpNFq469w',
    appId: '1:443780263124:web:dc585e4f4f7a9834ac1f41',
    messagingSenderId: '443780263124',
    projectId: 'domas-7a10f',
    authDomain: 'domas-7a10f.firebaseapp.com',
    storageBucket: 'domas-7a10f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv8em8UFNWHXzcsz95MGcXk8Tcf_u0wlI',
    appId: '1:443780263124:android:d8bcf262f319ef36ac1f41',
    messagingSenderId: '443780263124',
    projectId: 'domas-7a10f',
    storageBucket: 'domas-7a10f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSJVPEHA0coEKoz4hTA8xnld2Jj1r2wak',
    appId: '1:443780263124:ios:c2d784481eed8de8ac1f41',
    messagingSenderId: '443780263124',
    projectId: 'domas-7a10f',
    storageBucket: 'domas-7a10f.appspot.com',
    iosClientId: '443780263124-tplka2g0lkc6oqtvf5p6oe9egqf26jqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.doMas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSJVPEHA0coEKoz4hTA8xnld2Jj1r2wak',
    appId: '1:443780263124:ios:c2d784481eed8de8ac1f41',
    messagingSenderId: '443780263124',
    projectId: 'domas-7a10f',
    storageBucket: 'domas-7a10f.appspot.com',
    iosClientId: '443780263124-tplka2g0lkc6oqtvf5p6oe9egqf26jqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.doMas',
  );
}
